name: Fork code from github branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  contents: write

jobs:
  clone-and-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          repository: atishnaik8805/test-ui-code-fork-zip-repo
          ref: main
          submodules: recursive
      - name: Adding a submodule
        run: |
          git submodule add https://github.com/Umut-Tosun/e-commerce-app e-commerce-app
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Update submodule
        run: |
          git submodule update --init --recursive

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: e-commerce-app/package-lock.json
    - name: Install, build, and test submodule
      run: |
        cd e-commerce-app
        npm ci
        npm run build --if-present
        npm test
